[project]
name = "whatsmyip"
version = "0.2.1"
description = "Find out your IP address and the details of any IP address"
requires-python = ">=3.13"
dependencies = ["streamlit>=1.51.0", "pyperclip"]

[dependency-groups]
dev = ["black>=25.11.0"]